### ISSUE TITLE
Tooltips are often cut off

### ISSUE THREAD

**Issue by ethus3h** [compiz-reloaded/compiz#34] opened 2016-08-16 15:34 UTC
I see this fairly often. ![screenshot_2016 07 10_21 17 52](https://cloud.githubusercontent.com/assets/10457522/17705133/52618616-63a5-11e6-9c98-ae0f1de9255f.png)

**Comment by soreau** [comment] 2016-09-20 17:21
This is a known issue with emerald but does it happen with gtk-window-decorator?

**Comment by pwanchope** [comment] 2016-12-21 12:56
I used to see something similar with gtk-window-decorator, although I haven't seen it yet with compiz reloaded.  The problem was caused by the fade plugin.  Adding an exception so that Tooltip windows do not fade used to solve it.

**Comment by kn00tcn** [comment] 2017-04-06 03:54
if this helps, the cut off tooltip is the same size as the previously displayed tooltip if the previous tooltip is smaller than the new one

the quickest way to trigger it is to mouse over something that doesnt have a delay between tooltips, like xfce panel windows, while firefox seems to have a delay so i dont think i've ever seen them cut off

if animations are disabled for the tooltips, the cut off no longer happens

**actually, i just tried increasing the animation speed of closing, with disabled open animation, confirming that the problem happens while the closing animation is still going on, the new tooltip for whatever reason doesnt generate the new size, so nothing cuts off as long as the previous tooltip is not animating

maybe the code cant handle two tooltips at the same time? an easy workaround would be to wait until the animation finishes before showing the next tooltip (making sure to not queue up multiple obsolete ones like jquery kept doing by default on websites, meaning it should drop an(y) existing planned animation(s) if a new one was triggered)
**

**Comment by soreau** [comment] 2017-04-22 00:12
Can someone test this patch? http://sprunge.us/WFTX It should fix the problem but I'd like animations to be thoroughly tested with the patch installed.

**Comment by ethus3h** [comment] 2017-04-22 07:08
I'm using the patch now. It does seem to fix the issue. Thanks! I'll let you know if I see any side effects :)

**Closed** 2017-04-22 22:04 UTC
