### ISSUE TITLE
Freeze on pressing Alt+Tab

### ISSUE THREAD

**Issue by arifcatalyst** [compiz-reloaded/compiz#98] opened 2017-12-22 17:31 UTC
My system freezes on pressing Alt+Tab. It only happens when using Compiz.

**Comment by arifcatalyst** [comment] 2017-12-22 19:08
The recent update in `xorg-server-common` `xorg-server ` `xorg-server-devel`  `xorg-server-xephyr` breaks compiz `Switch` plugin

**Comment by soreau** [comment] 2017-12-22 21:04
A system freeze typically points to a problem outside of compiz. As you suggested, it might be with a recent driver update. I'm guessing by switch plugin you mean application switcher. Recently [a compiz commit](https://github.com/compiz-reloaded/compiz/commit/3aa89795ed639b562dd440e6a43cc496825d406f) was made to disable mipmaps by default. Does it help if you disable mipmaps?

**Comment by arifcatalyst** [comment] 2017-12-22 21:39
No, disabling mipmaps doesn't help. It only freezes with Compiz WM, with `Xfwm` I don't have any freeze issue with these drivers.
Yes I mean `Application Switcher` 

Right now, I have downgraded `Xorg` packages and I don't have any freezes, so it's definitely something wrong with `Xorg` or `Compiz`

**Comment by soreau** [comment] 2017-12-22 21:45
If downgrading X packages fix the problem, it's a problem with X or your graphics drivers. xfwm4 isn't much of a test because it doesn't have the same switcher code as compiz. It sounds like you need to file a bug at bugs.freedesktop.org for the relevant component, possibly under xorg>Server/General component. Closing for now, feel free to comment further here.

**Comment by arifcatalyst** [comment] 2017-12-22 21:50
Can't there be any upstream issue in Compiz code here ? That is there are some changes in the code of `Xorg` and Compiz need to incorporate those changes ? Just guessing.

**Comment by soreau** [comment] 2017-12-22 21:58
I'm guessing it may be that you need to update packages in addition to xserver, like mesa and/or xf86-video-$driver. I doubt that there was some X related API change that require compiz to be patched but it's not impossible.

**Comment by arifcatalyst** [comment] 2017-12-22 22:00
I got these update 
          ```
 lib32-mesa-17.3.1-0  mesa-17.3.1-0  mesa-vdpau-17.3.1-0
             xorg-server-1.19.6-0  xorg-server-common-1.19.6-0
             xorg-server-devel-1.19.6-0  xorg-server-xephyr-1.19.6-0

```
And I had to revert these package to make it work back again.

**Comment by soreau** [comment] 2017-12-22 22:04
Did you try to rebuild compiz after the update in case of some ABI change?

**Comment by arifcatalyst** [comment] 2017-12-22 22:05
I'll try and report back if it fixes.

**Comment by arifcatalyst** [comment] 2017-12-23 07:43
I installed the updated packages and rebuilt compiz from aur-git package. Kernel panics retain.

**Comment by soreau** [comment] 2017-12-23 07:59
It works here with version 1.19.3, which version are you downgrading to? For what it's worth, I don't believe these are kernel panics. Usually a panic is accompanied by blinking keyboard LEDs. This is probably a lockup of xserver or compiz. You can try to ssh in or ping from another machine to see if it's still responsive while frozen.

**Comment by arifcatalyst** [comment] 2017-12-23 08:04
Freeze causes on 1.19.6` version. Yes, it may not be a kernel panic, just a lockup of xserver or compiz

**Comment by soreau** [comment] 2017-12-23 08:11
Which version of X works for you?

**Comment by arifcatalyst** [comment] 2017-12-23 08:12
Version `1.19.5-1` works for me

**Comment by soreau** [comment] 2017-12-23 08:19
What switchers does it happen with? Only application switcher or Static Application Switcher too? Shift, Ring or Stack Switcher?

**Comment by arifcatalyst** [comment] 2017-12-23 08:21
`Application switcher` and `Static Application Switcher`

**Comment by soreau** [comment] 2017-12-23 08:28
I suggest you file a bug against xserver with this information. It would be nice to bisect the xserver to see what commit causes the trouble, maybe I'll get a wild hair and try to reproduce it.

**Comment by arifcatalyst** [comment] 2017-12-23 08:29
You can't reproduce the issue with X `1.19.6` ?

**Comment by soreau** [comment] 2017-12-23 08:31
I don't know because I haven't tried it.

**Comment by arifcatalyst** [comment] 2017-12-23 08:34
I am using `compicc` plugin too and there was some recent commits related to switcher plugin which may be the reason for lockup. I'll report back after removing this plugin.

**Comment by soreau** [comment] 2017-12-23 08:37
If that is the problem, downgrading X shouldn't fix it. Also you can simply disable it to check.

**Comment by arifcatalyst** [comment] 2017-12-23 08:39
Yeah, I even removed it but the problem persists.

**Comment by arifcatalyst** [comment] 2017-12-23 08:40
I will file a bug on X server and let you know

**Comment by arifcatalyst** [comment] 2017-12-23 16:34
I have filed a bug, but the people at the Manjaro forum are suggesting that there might be a bug in the upstream software that needs to be fixed for Xorg 1.19.6.

**Comment by arifcatalyst** [comment] 2017-12-23 16:37
Could you please try reproducing this issue with `X` `1.19.6` and open the issue since it's still not clear if it's Compiz or `X`

**Comment by soreau** [comment] 2017-12-23 22:10
Can you post the link to the bug report please?

**Comment by arifcatalyst** [comment] 2017-12-24 09:12
[https://bugs.freedesktop.org/show_bug.cgi?id=104375](url)

**Comment by arifcatalyst** [comment] 2017-12-24 17:35
@soreau I have nailed it, the issue is with the `Compicc` plugin. When `Compicc` plugin is installed not even activated, it freezes when Alt+Tab is pressed with `X1.19.6`

**Comment by soreau** [comment] 2017-12-24 18:58
That doesn't really make sense. If the plugin is disabled, it shouldn't affect anything. And it doesn't happen when compicc is installed if you're using X 1.19.5-1? a real head scratcher

**Comment by arifcatalyst** [comment] 2017-12-24 19:05
You are right, there are two issues right now with the freeze. 
One -when using one of my configuration and `compicc` plugin disabled,it starts to freeze, so the culprit in this case can be my configuration of Compiz, that's the reason I said even when the plugin is disabled.

Second - When using the default config and `compicc` plugin disabled, no more freezes but when I enable the plugin, it starts to freeze, so in this case the culprit is `Compicc` plugin 

And Finally, there is no freezes with `Compicc` plugin  enabled with `X 1.19.5-1`

**Comment by soreau** [comment] 2017-12-24 19:08
And there might be another bug indeed, as there is a known freeze with these switcher plugins and mipmaps enabled, so make sure to keep an eye on that too.

**Comment by arifcatalyst** [comment] 2017-12-24 19:12
It's not the `mipmaps` issue here.

**Comment by soreau** [comment] 2017-12-25 02:01
I tested on X 1.19.99 with amdgpu+DRI3 and was not able to reproduce the problem.

**Comment by arifcatalyst** [comment] 2017-12-25 08:52
> I tested on X 1.19.99 with amdgpu+DRI3 and was not able to reproduce the problem.

Tell me your setup, and my version of `X` is `1.19.6-0` on which freeze are occurring.

**Comment by soreau** [comment] 2017-12-25 16:42
Intel i5, Radeon RX 460, 16GB RAM, 64bit Linux. Does the freeze happen immediately for you every time trying to invoke application switcher or does it take more than one try?

**Comment by arifcatalyst** [comment] 2017-12-25 19:09
Try with these apps 
`X-1.19.6-0` 
`Compiz-0.8.15`  with `main` `extra`  `experimental` `compicc` plugin installed and `blur` with `mipmaps` blur and `compicc` plugin enabled.

And the freeze happens immediately.

**Comment by soreau** [comment] 2017-12-25 19:16
Since you can reproduce the problem, you are in the position to bisect X, the result of which you could post to the bug report. I'm not interested in trying to reproduce the problem, other than a quick test which revealed this is not a general problem with compiz or X. You should follow up on the freedesktop.org report from here, adding your X log and say what video card you're using.

**Closed by soreau** 2017-12-25 19:16 UTC

**Comment by arifcatalyst** [comment] 2017-12-28 18:46
@soreau  The problem is on `Compiz 0.9` too. Here is the commit which tries to fix the issue [https://github.com/manjaro/packages-community/commit/88dea2df4a18934385f61c2298718dae4f0e86bc](url)

**Comment by soreau** [comment] 2017-12-28 20:27
@arifcatalyst As far as I can tell, that patch doesn't change any code but instead changes a lot of default metadata. If that patch fixes anything, it's surely a workaround by changing settings.

**Comment by arifcatalyst** [comment] 2017-12-31 17:51
@soreau It is the `Emerald-window-decorator` which is causing the uphill. You can try reproducing this issue with `Xorg >1.19.6`  Can you please look into ?
