### ISSUE TITLE
Drawing using the annotate plugin causes glitchy behaviour of shadows (they change to black and look weird and such).

### ISSUE THREAD

**Issue by ethus3h** [compiz-reloaded/compiz#36] opened 2016-08-19 20:54 UTC
Drawing using the annotate plugin causes glitchy behaviour of shadows (they change to black and look weird and such).

Using the Emerald theme linked in this comment: https://github.com/compiz-reloaded/emerald/issues/12#issuecomment-236392358 .

Possibly related to that issue?

**Comment by soreau** [comment] 2016-09-11 19:42
I can't reproduce this. Perhaps a driver issue?

**Comment by ethus3h** [comment] 2016-09-11 21:17
Ah, not sure. I'll have a computer with Intel drivers in a bit, so I can see if it happens then. Thanks! :)

**Comment by soreau** [comment] 2016-09-12 19:33
Closing for now

**Closed by soreau** 2016-09-12 19:33 UTC
